### ISSUE TITLE
1.44

### ISSUE THREAD

**Issue by Tr1lla** [nshusa/native-sprite-packer#15]
Hey man, I cant find the download link to the 1.44 version for converting from galkons, anywhere, would you please link it to me, thanks :)

**Comment by nshusa** [comment]
@Tr1lla I don't have it anymore.

**Comment by nshusa** [comment]
@Tr1lla 

[1.44](https://github.com/nshusa/native-sprite-packer/tree/5626721f137a394a4ea2ddb73f7aeb3109dd32d3)
